-- =================================================
--   colors.lua — generated by Matugen
--   DO NOT EDIT — re-run matugen to regenerate
-- =================================================

-- Primary palette
primary          = "rgba({{ colors.primary.default.hex_alpha_stripped }})"
on_primary       = "rgba({{ colors.on_primary.default.hex_alpha_stripped }})"
primary_container     = "rgba({{ colors.primary_container.default.hex_alpha_stripped }})"
on_primary_container  = "rgba({{ colors.on_primary_container.default.hex_alpha_stripped }})"

-- Secondary palette
secondary        = "rgba({{ colors.secondary.default.hex_alpha_stripped }})"
on_secondary     = "rgba({{ colors.on_secondary.default.hex_alpha_stripped }})"
secondary_container   = "rgba({{ colors.secondary_container.default.hex_alpha_stripped }})"
on_secondary_container = "rgba({{ colors.on_secondary_container.default.hex_alpha_stripped }})"

-- Tertiary palette
tertiary         = "rgba({{ colors.tertiary.default.hex_alpha_stripped }})"
on_tertiary      = "rgba({{ colors.on_tertiary.default.hex_alpha_stripped }})"
tertiary_container    = "rgba({{ colors.tertiary_container.default.hex_alpha_stripped }})"
on_tertiary_container = "rgba({{ colors.on_tertiary_container.default.hex_alpha_stripped }})"

-- Surface / background
background       = "rgba({{ colors.background.default.hex_alpha_stripped }})"
on_background    = "rgba({{ colors.on_background.default.hex_alpha_stripped }})"
surface          = "rgba({{ colors.surface.default.hex_alpha_stripped }})"
on_surface       = "rgba({{ colors.on_surface.default.hex_alpha_stripped }})"
surface_variant  = "rgba({{ colors.surface_variant.default.hex_alpha_stripped }})"
on_surface_variant = "rgba({{ colors.on_surface_variant.default.hex_alpha_stripped }})"

-- Error
error            = "rgba({{ colors.error.default.hex_alpha_stripped }})"
on_error         = "rgba({{ colors.on_error.default.hex_alpha_stripped }})"
error_container  = "rgba({{ colors.error_container.default.hex_alpha_stripped }})"
on_error_container = "rgba({{ colors.on_error_container.default.hex_alpha_stripped }})"

-- Outline / shadow
outline          = "rgba({{ colors.outline.default.hex_alpha_stripped }})"
outline_variant  = "rgba({{ colors.outline_variant.default.hex_alpha_stripped }})"
shadow           = "rgba({{ colors.shadow.default.hex_alpha_stripped }})"

-- Hyprland border helpers (with custom alpha)
active_border    = "rgba({{ colors.primary.default.hex_alpha_stripped | set_alpha: 1.0 }})"
inactive_border  = "rgba({{ colors.surface_variant.default.hex_alpha_stripped | set_alpha: 0.6 }})"
shadow_color     = "rgba({{ colors.shadow.default.hex_alpha_stripped | set_alpha: 0.8 }})"
