-- =================================================
--   colors.lua — generated by Matugen
--   DO NOT EDIT — re-run matugen to regenerate
-- =================================================

-- Primary palette
primary          = "rgba(FFBB6EFF)"
on_primary       = "rgba(482900FF)"
primary_container     = "rgba(E99D3EFF)"
on_primary_container  = "rgba(351D00FF)"

-- Secondary palette
secondary        = "rgba(EABF91FF)"
on_secondary     = "rgba(452B09FF)"
secondary_container   = "rgba(5F411DFF)"
on_secondary_container = "rgba(FFDAB4FF)"

-- Tertiary palette
tertiary         = "rgba(C2D163FF)"
on_tertiary      = "rgba(2D3400FF)"
tertiary_container    = "rgba(A7B54BFF)"
on_tertiary_container = "rgba(202500FF)"

-- Surface / background
background       = "rgba(18120CFF)"
on_background    = "rgba(EEE0D5FF)"
surface          = "rgba(18120CFF)"
on_surface       = "rgba(EEE0D5FF)"
surface_variant  = "rgba(524436FF)"
on_surface_variant = "rgba(D7C3B1FF)"

-- Error
error            = "rgba(FFB4ABFF)"
on_error         = "rgba(690005FF)"
error_container  = "rgba(93000AFF)"
on_error_container = "rgba(FFDAD6FF)"

-- Outline / shadow
outline          = "rgba(9F8E7DFF)"
outline_variant  = "rgba(524436FF)"
shadow           = "rgba(000000FF)"

-- Hyprland border helpers (with custom alpha)
active_border    = "rgba(FFBB6EFF)"
inactive_border  = "rgba(52443699)"
shadow_color     = "rgba(000000CC)"
