-- =================================================
--   colors.lua — generated by Matugen
--   DO NOT EDIT — re-run matugen to regenerate
-- =================================================

-- Primary palette
primary          = "rgba(EFBE81FF)"
on_primary       = "rgba(462A00FF)"
primary_container     = "rgba(B48951FF)"
on_primary_container  = "rgba(000000FF)"

-- Secondary palette
secondary        = "rgba(DDC2A5FF)"
on_secondary     = "rgba(3E2D19FF)"
secondary_container   = "rgba(56442DFF)"
on_secondary_container = "rgba(F7DCBDFF)"

-- Tertiary palette
tertiary         = "rgba(C2CC8DFF)"
on_tertiary      = "rgba(2C3404FF)"
tertiary_container    = "rgba(8C965BFF)"
on_tertiary_container = "rgba(000000FF)"

-- Surface / background
background       = "rgba(16130FFF)"
on_background    = "rgba(EAE1DAFF)"
surface          = "rgba(16130FFF)"
on_surface       = "rgba(EAE1DAFF)"
surface_variant  = "rgba(4F453AFF)"
on_surface_variant = "rgba(D3C4B5FF)"

-- Error
error            = "rgba(FFB4ABFF)"
on_error         = "rgba(690005FF)"
error_container  = "rgba(93000AFF)"
on_error_container = "rgba(FFDAD6FF)"

-- Outline / shadow
outline          = "rgba(9C8E81FF)"
outline_variant  = "rgba(4F453AFF)"
shadow           = "rgba(000000FF)"

-- Hyprland border helpers (with custom alpha)
active_border    = "rgba(EFBE81FF)"
inactive_border  = "rgba(4F453A99)"
shadow_color     = "rgba(000000CC)"
